- name: Deploy Strapi and Frontend via IAP
  hosts: webservers
  become: yes
  gather_facts: no  # <--- MUST BE NO
  tasks:
    - name: Create project folder
      file:
        path: /opt/my-app
        state: directory
        owner: ubuntu

    - name: Configure Docker Auth on VM
      shell: gcloud auth configure-docker {{ region }}-docker.pkg.dev --quiet

    - name: Create .env file
      copy:
        dest: /opt/my-app/.env
        content: |
          STRAPI_IMAGE={{ strapi_image }}
          DATABASE_HOST={{ db_host }}
          DATABASE_PASSWORD={{ db_password }}
          DATABASE_NAME=strapi
          DATABASE_USERNAME=strapi
          NODE_ENV=production

    - name: Copy docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /opt/my-app/docker-compose.yml

    - name: Pull and Start
      shell: |
        cd /opt/my-app
        docker compose pull
        docker compose up -d --remove-orphans