; [webservers]
; # CHANGE root to ubuntu
; elastic-search zone=asia-south1-a ansible_user=ubuntu

; [webservers:vars]
; # Added --quiet and --project to ensure no prompts
; ansible_ssh_common_args='-o ProxyCommand="gcloud compute start-iap-tunnel {{ inventory_hostname }} 22 --listen-on-stdin --zone={{ zone }} --quiet --project={{ lookup(\"env\", \"PROJECT_ID\") }}"'
[webservers]
# This variable 'target_host' is passed from the workflow
{{ target_host }} ansible_user=ubuntu