[webservers]
elastic-search zone=asia-south1-a ansible_user=ubuntu

[webservers:vars]
# Use start-iap-tunnel for a more stable connection
ansible_ssh_common_args='-o ProxyCommand="gcloud compute start-iap-tunnel {{ inventory_hostname }} 22 --listen-on-stdin --zone={{ zone }}"'