[webservers]
elastic-search ansible_host=elastic-search zone=asia-south1-a ansible_user=root

[webservers:vars]
# This defines the proxy command for everything in the [webservers] group
ansible_ssh_common_args='-o ProxyCommand="gcloud compute ssh --zone={{ zone }} {{ inventory_hostname }} --tunnel-through-iap --dry-run"'